platform :ios, '14.0'

target 'MoviesDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesDB
  pod 'Alamofire', '~> 5.2'

  target 'MoviesDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesDBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
